title: "Zigで学ぶブロックチェーン"
summary: "Zig言語を使ってブロックチェーンを実装する"
topics: ["Zig", "BlockChain"]
published: false
price: 0
chapters:
  - はじめに
  - ブロックチェーンの基本的な実装
  - ネットワーク化と分散ノード
  - コンセンサスアルゴリズム（PoWとPoS）
  - スマートコントラクトとEVM互換
  - 最新技術への対応と発展的トピック
