title: "Zig言語で学ぶブロックチェーン"
summary: "本書の目的は、Zig言語でブロックチェーンをゼロから作り上げる過程を通じてその仕組みへの理解を深め、最終的にEVM互換のチェーンを自分で動かせるようになることです。堅苦しい教科書ではなく、手を動かしながら学べる工作キットのような感覚で楽しんでいただければ幸いです。"
topics: ["Zig", "BlockChain"]
published: false
price: 500
chapters:
  - intro
  - chapter1
  - ネットワーク化と分散ノード
  - コンセンサスアルゴリズム（PoWとPoS）
  - スマートコントラクトとEVM互換
  - 最新技術への対応と発展的トピック
