title: "Zig言語で学ぶブロックチェイン"
summary: "本書の目的は、Zig言語でブロックチェインをゼロから作り上げる過程を通じてその仕組みへの理解を深め、最終的にEVM互換のチェインを自分で動かせるようになることです。堅苦しい教科書ではなく、手を動かしながら学べる工作キットのような感覚で楽しんでいただければ幸いです。"
topics: ["Zig", "BlockChain"]
published: false
price: 500
chapters:
  - chapter1
  - chapter2
  - chapter3
  - chapter4
  - chapter5
  - chapter6
  - chapter7
  - chapter8
  - chapter9
  - chapter10
  - chapter11
